---
- hosts: all
  become: true
  
  tasks:
  - name: login to aws
    shell: $(/usr/bin/aws ecr get-login --no-include-email --region ap-south-1)

  - name: remove the image
    command: docker rmi 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
    ignore_errors: yes

  - name: docker pull
    command: docker pull 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
    ignore_errors: yes

  - name: build the images
    command: docker build -t nodejs .
    args:
      chdir: /opt/docker/docker-nodejs

  - name: tag the images
    command: docker tag nodejs:latest 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest

  - name: push the image
    command: docker push 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest

 # - name: pull the image 
  #  command: docker pull 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
 # - name: stop the container
 #   command: docker stop nodejs-devops-container
 #   ignore_errors: yes


  #- name: stop rm container
    #command: docker rm nodejs-devops-container
    #ignore_errors: yes

  #- name: create container using nodejs devops image
   # command: docker run -d --name nodejs-devops-container -p 8080:8080 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest