---
- hosts: ansible
  become: true
  tasks:
   
  #- name: login to aws
    #shell: "$(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 583044482327.dkr.ecr.ap-south-1.amazonaws.com)
  - name: remove the image
    command: docker rmi 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
    ignore_errors: yes
 
  - name: build the images
    command: docker build -t nodejs .
    args:
      chdir: /opt/docker/docker-nodejs

  - name: tag the images
    command: docker tag nodejs:latest 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest

 # - name: remove the image
  #  command: docker rmi 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
 # - name: login to the ECR
  #  shell: $(/usr/bin/aws ecr get-login --no-include-email --region ap-south-1) 
  
  - name: push the image
    command: docker push 583044482327.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest



